In [306]:
import pandas as pd
df = pd.read_csv("../Datasets/car_rental_dirty_dataset_new1.csv")

In [ ]:
# Initial Data Exploration (EDA)

print("Dataset Shape:")
print(df.shape)

print("\nFirst 5 rows of dataset:")
display(df.head())

print("\nDataset Information:")
df.info()

print("\nSummary Statistics:")
display(df.describe(include='all'))

print("\nMissing Values in Each Column:")
print(df.isna().sum().sort_values(ascending=False))

print("\nDuplicate Reservation_IDs:")
print(df['Reservation_ID'].duplicated().sum())

print("\nUnique Vehicle_IDs:")
print(df['Vehicle_ID'].nunique())

print("\nUnique City Values:")
print(df['City'].unique())

print("\nUnique Payment Methods:")
print(df['Payment'].unique())

print("\nSample Odometer Values:")
display(df[['Odo_Start','Odo_End']].head())

print("\nSample Fuel Levels:")
print(df['Fuel_Level'].unique())

Dataset Shape:
(5000, 21)

First 5 rows of dataset:

,Reservation_ID,Customer_ID,Vehicle_ID,Vehicle_Class,Booking_Status,Booking_TS,Pickup_TS,Return_TS,Odo_Start,Odo_End,Fuel_Level,Rate,Promo_Code,City,GPS_Lat,GPS_Lon,Speed,Payment,Driver_License,Damage_Flag,Notes
0,RES-00001,CUST-1675,CAR-014,Hatchback,No_Show,02/13/2025 07:56,2025-02-18T07:56,18-02-2025 09:56,57815,"58,065",0.10,$20/day,NaN,New Delhi,12.908959,77.604003,133kmh,cash,DL-2699413330,Major,Customer satisfied with ride
1,RES-00002,CUST-0853,CAR230,SUV,Cancelled,08-02-2025 20:56,16-02-2025 20:56,2025-02-17 07:56,"77,762",77766km,NaN,₹ 2000 / day,NEW10,mumbai,12.946286,77.586710,55,CASH,DL-9806685378,Major,Customer requested early pickup
2,RES-00003,CUST-1181,CAR-001,Suzuki,Completed,2025-03-09T00:07,10-03-2025 00:07,12-03-2025 23:07,"57,856","58,238",30%,2000/day,DISC20,delhi,12.914102,77.627323,128 km/h,upi,DL-9542219877,Minor,Customer reported minor scratch on door
3,RES-00004,CUST-0182,CAR-434,Suzuki,Cancelled,04-01-2025 02:16,2025-01-11 02:16,11-01-2025 22:16,"59,967",60239km,0.5,1500/day,SAVE50,delhi,12.873192,77.635268,25 km/h,cash,DL-4380657786,NaN,Customer requested early pickup
4,RES-00005,CUST-0356,CAR-121,Suzuki,No_Show,2025-05-04T04:22,2025-05-09T04:22,2025-05-10 11:22,"24,261","24,524",75,USD 25/day,DISC20,bangalore,12.919640,77.598891,26kmh,-,DL-6429812852,Minor,AC performance slightly low

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Reservation_ID  5000 non-null   str
 1   Customer_ID     5000 non-null   str
 2   Vehicle_ID      5000 non-null   str
 3   Vehicle_Class   5000 non-null   str
 4   Booking_Status  5000 non-null   str
 5   Booking_TS      5000 non-null   str
 6   Pickup_TS       5000 non-null   str
 7   Return_TS       5000 non-null   str
 8   Odo_Start       5000 non-null   str
 9   Odo_End         5000 non-null   str
 10  Fuel_Level      4359 non-null   str
 11  Rate            4530 non-null   str
 12  Promo_Code      3980 non-null   str
 13  City            4687 non-null   str
 14  GPS_Lat         5000 non-null   float64
 15  GPS_Lon         5000 non-null   float64
 16  Speed           3991 non-null   str
 17  Payment         4641 non-null   str
 18  Driver_License  5000 non-null   str
 19  Damage_Flag     3351 non-null   str
 20  Notes           4167 non-null   str
dtypes: float64(2), str(19)
memory usage: 820.4 KB

Summary Statistics:

,Reservation_ID,Customer_ID,Vehicle_ID,Vehicle_Class,Booking_Status,Booking_TS,Pickup_TS,Return_TS,Odo_Start,Odo_End,Fuel_Level,Rate,Promo_Code,City,GPS_Lat,GPS_Lon,Speed,Payment,Driver_License,Damage_Flag,Notes
count,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,4359,4530,3980,4687,5000.000000,5000.000000,3991,4641,5000,3351,4167
unique,4527,1813,601,8,3,4521,4520,4522,4480,4482,14,11,4,16,NaN,NaN,364,14,1813,2,10
top,RES-00016,CUST-0356,CAR-149,Creta,No_Show,04/18/2025 08:13,11-02-2025 20:33,24-04-2025 06:09,"75,393","22,720",1.0,1800 perday,NEW10,bangalore,NaN,NaN,fast,upi,DL-6429812852,Major,Navigation system malfunction reported
freq,2,9,18,749,1702,2,3,3,3,3,343,445,1030,319,NaN,NaN,1042,387,9,1688,459
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.899823,77.600168,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.028912,0.028970,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.850062,77.550003,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.874808,77.575764,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.900507,77.599728,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.924625,77.625366,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.949990,77.649963,NaN,NaN,NaN,NaN,NaN

Missing Values in Each Column:
Damage_Flag       1649
Promo_Code        1020
Speed             1009
Notes              833
Fuel_Level         641
Rate               470
Payment            359
City               313
Booking_Status       0
Reservation_ID       0
Vehicle_Class        0
Vehicle_ID           0
Customer_ID          0
Odo_End              0
Pickup_TS            0
Return_TS            0
Odo_Start            0
Booking_TS           0
GPS_Lat              0
GPS_Lon              0
Driver_License       0
dtype: int64

Duplicate Reservation_IDs:
473

Unique Vehicle_IDs:
601

Unique City Values:
<StringArray>
['New Delhi',    'mumbai',     'delhi', 'bangalore',   'chennai',         nan,
    'Mumbai', 'Bengaluru',       'MUM',   'Chennai',       'BLR',     'Delhi',
       'CHN',   'unknown',    'Bombay',       'blr',     'DELHI']
Length: 17, dtype: str

Unique Payment Methods:
<StringArray>
[       'cash',        'CASH',        'upi ',           '-',       ' card',
      'wallet',  'netbanking',  'Debit Card', 'Credit Card',           nan,
        'CARD',         'upi',      'Wallet',        'card',         'UPI']
Length: 15, dtype: str

Sample Odometer Values:

  Odo_Start  Odo_End
0     57815   58,065
1    77,762  77766km
2    57,856   58,238
3    59,967  60239km
4    24,261   24,524

Sample Fuel Levels:
<StringArray>
['0.10',    nan,  '30%',  '0.5',   '75',  '75%', '0.75', '100%',  '25%',
  '1.0',  '10%',   '50',  '50%', '0.30', '0.25']
Length: 15, dtype: str

## 1. Vehicle_ID trimming and canonical case.

In [308]:
unique_vid = df['Vehicle_ID'].nunique()

# Inspect raw Vehicle_ID values
print(f"Shape: {df.shape}")
print(f"Unique Vehicle_IDs (raw): {unique_vid}")
print(sorted(df['Vehicle_ID'].dropna().unique()))
print(f"\n{df['Vehicle_ID'].value_counts().sort_index()}")

Shape: (5000, 21)
Unique Vehicle_IDs (raw): 601
[' CAR-010 ', ' CAR-014 ', ' CAR-015 ', ' CAR-027 ', ' CAR-034 ', ' CAR-045 ', ' CAR-047 ', ' CAR-063 ', ' CAR-066 ', ' CAR-070 ', ' CAR-089 ', ' CAR-091 ', ' CAR-100 ', ' CAR-101 ', ' CAR-104 ', ' CAR-112 ', ' CAR-128 ', ' CAR-133 ', ' CAR-135 ', ' CAR-137 ', ' CAR-138 ', ' CAR-148 ', ' CAR-164 ', ' CAR-169 ', ' CAR-188 ', ' CAR-190 ', ' CAR-193 ', ' CAR-195 ', ' CAR-206 ', ' CAR-213 ', ' CAR-263 ', ' CAR-275 ', ' CAR-282 ', ' CAR-286 ', ' CAR-301 ', ' CAR-303 ', ' CAR-317 ', ' CAR-333 ', ' CAR-340 ', ' CAR-343 ', ' CAR-347 ', ' CAR-369 ', ' CAR-374 ', ' CAR-379 ', ' CAR-381 ', ' CAR-385 ', ' CAR-388 ', ' CAR-396 ', ' CAR-402 ', ' CAR-430 ', ' CAR-432 ', ' CAR-435 ', ' CAR-436 ', ' CAR-440 ', ' CAR-453 ', ' CAR-471 ', ' CAR-477 ', ' CAR-480 ', ' CAR-503 ', ' CAR-504 ', ' CAR-520 ', ' CAR-533 ', ' CAR-538 ', ' CAR-564 ', ' CAR-572 ', ' CAR-583 ', ' CAR-591 ', ' CAR-594 ', ' CAR-599 ', 'CAR 005', 'CAR 011', 'CAR 020', 'CAR 030', 'CAR 031', 'CAR 043', 'CAR 056', 'CAR 060', 'CAR 074', 'CAR 081', 'CAR 086', 'CAR 103', 'CAR 117', 'CAR 119', 'CAR 127', 'CAR 131', 'CAR 136', 'CAR 141', 'CAR 145', 'CAR 161', 'CAR 166', 'CAR 171', 'CAR 203', 'CAR 212', 'CAR 216', 'CAR 219', 'CAR 223', 'CAR 236', 'CAR 242', 'CAR 255', 'CAR 261', 'CAR 290', 'CAR 296', 'CAR 304', 'CAR 305', 'CAR 349', 'CAR 351', 'CAR 356', 'CAR 359', 'CAR 362', 'CAR 368', 'CAR 389', 'CAR 398', 'CAR 400', 'CAR 421', 'CAR 422', 'CAR 425', 'CAR 433', 'CAR 444', 'CAR 449', 'CAR 454', 'CAR 462', 'CAR 484', 'CAR 485', 'CAR 498', 'CAR 508', 'CAR 511', 'CAR 515', 'CAR 522', 'CAR 535', 'CAR 551', 'CAR 552', 'CAR 553', 'CAR 559', 'CAR 563', 'CAR 565', 'CAR 575', 'CAR 588', 'CAR 598', 'CAR-001 ', 'CAR-002', 'CAR-009 ', 'CAR-012', 'CAR-018', 'CAR-023', 'CAR-024 ', 'CAR-026', 'CAR-032 ', 'CAR-035', 'CAR-036', 'CAR-048', 'CAR-049', 'CAR-052', 'CAR-057 ', 'CAR-058 ', 'CAR-061', 'CAR-062', 'CAR-065', 'CAR-069', 'CAR-071', 'CAR-073 ', 'CAR-075', 'CAR-078', 'CAR-082', 'CAR-092 ', 'CAR-093 ', 'CAR-094', 'CAR-097 ', 'CAR-099 ', 'CAR-113 ', 'CAR-114 ', 'CAR-118', 'CAR-121', 'CAR-124 ', 'CAR-125', 'CAR-130', 'CAR-132', 'CAR-142 ', 'CAR-144', 'CAR-146', 'CAR-147', 'CAR-149 ', 'CAR-155 ', 'CAR-162 ', 'CAR-172', 'CAR-182', 'CAR-183 ', 'CAR-187', 'CAR-189 ', 'CAR-196', 'CAR-202', 'CAR-204 ', 'CAR-205 ', 'CAR-215', 'CAR-218 ', 'CAR-226', 'CAR-228', 'CAR-231', 'CAR-233', 'CAR-234', 'CAR-240 ', 'CAR-241', 'CAR-246 ', 'CAR-247 ', 'CAR-256', 'CAR-269', 'CAR-271', 'CAR-274', 'CAR-277', 'CAR-280', 'CAR-281 ', 'CAR-284', 'CAR-291 ', 'CAR-294', 'CAR-297 ', 'CAR-298', 'CAR-300 ', 'CAR-310 ', 'CAR-322', 'CAR-324 ', 'CAR-327', 'CAR-328', 'CAR-329', 'CAR-331', 'CAR-332 ', 'CAR-339', 'CAR-341 ', 'CAR-345', 'CAR-348 ', 'CAR-370', 'CAR-377 ', 'CAR-394 ', 'CAR-404 ', 'CAR-405 ', 'CAR-410 ', 'CAR-415', 'CAR-416', 'CAR-418', 'CAR-426', 'CAR-427 ', 'CAR-429 ', 'CAR-434 ', 'CAR-438 ', 'CAR-442 ', 'CAR-445', 'CAR-446', 'CAR-448 ', 'CAR-450 ', 'CAR-451', 'CAR-452 ', 'CAR-460', 'CAR-464', 'CAR-468 ', 'CAR-476', 'CAR-482', 'CAR-486 ', 'CAR-494', 'CAR-502 ', 'CAR-507 ', 'CAR-512', 'CAR-517', 'CAR-521', 'CAR-523', 'CAR-524', 'CAR-527 ', 'CAR-530 ', 'CAR-534 ', 'CAR-539', 'CAR-541', 'CAR-543 ', 'CAR-544 ', 'CAR-546 ', 'CAR-550', 'CAR-558 ', 'CAR-560', 'CAR-561', 'CAR-568', 'CAR-569 ', 'CAR-576 ', 'CAR-578 ', 'CAR-580 ', 'CAR-597 ', 'CAR-600 ', 'CAR003', 'CAR013', 'CAR017', 'CAR021', 'CAR046', 'CAR083', 'CAR090', 'CAR096', 'CAR107', 'CAR111', 'CAR115', 'CAR122', 'CAR139', 'CAR143', 'CAR156', 'CAR159', 'CAR160', 'CAR163', 'CAR170', 'CAR173', 'CAR177', 'CAR180', 'CAR181', 'CAR198', 'CAR208', 'CAR214', 'CAR222', 'CAR230', 'CAR235', 'CAR245', 'CAR248', 'CAR253', 'CAR265', 'CAR268', 'CAR288', 'CAR306', 'CAR308', 'CAR314', 'CAR318', 'CAR337', 'CAR350', 'CAR358', 'CAR378', 'CAR393', 'CAR399', 'CAR407', 'CAR411', 'CAR417', 'CAR424', 'CAR447', 'CAR457', 'CAR458', 'CAR459', 'CAR461', 'CAR472', 'CAR475', 'CAR479', 'CAR493', 'CAR506', 'CAR525', 'CAR531', 'CAR536', 'CAR540', 'CAR555', 'CAR567', 'CAR577', 'CAR581', 'CAR584', 'CAR585', 'CAR586', 'CAR595', 'CAR_006', 'CAR_019', 'CAR_022', 'CAR_029', 'CAR_033', 'CAR_041', 'CAR_053', 'CAR_055', 'CAR_059', 'CAR_064', 'CAR_095', 'CAR_098', 'CAR_102', 'CAR_105', 'CAR_106', 'CAR_110', 'CAR_116', 'CAR_126', 'CAR_150', 'CAR_151', 'CAR_154', 'CAR_167', 'CAR_174', 'CAR_184', 'CAR_192', 'CAR_197', 'CAR_207', 'CAR_209', 'CAR_217', 'CAR_221', 'CAR_224', 'CAR_232', 'CAR_243', 'CAR_250', 'CAR_259', 'CAR_266', 'CAR_267', 'CAR_278', 'CAR_279', 'CAR_289', 'CAR_309', 'CAR_313', 'CAR_315', 'CAR_325', 'CAR_330', 'CAR_334', 'CAR_355', 'CAR_360', 'CAR_361', 'CAR_363', 'CAR_365', 'CAR_375', 'CAR_376', 'CAR_383', 'CAR_392', 'CAR_419', 'CAR_437', 'CAR_439', 'CAR_443', 'CAR_456', 'CAR_463', 'CAR_465', 'CAR_473', 'CAR_481', 'CAR_490', 'CAR_492', 'CAR_496', 'CAR_499', 'CAR_509', 'CAR_513', 'CAR_537', 'CAR_547', 'CAR_556', 'CAR_557', 'CAR_589', 'CAR_592', 'CAR_593', 'UNKNOWN', 'car-007', 'car-025', 'car-028', 'car-042', 'car-044', 'car-050', 'car-051', 'car-054', 'car-067', 'car-068', 'car-080', 'car-084', 'car-087', 'car-088', 'car-109', 'car-134', 'car-140', 'car-153', 'car-157', 'car-158', 'car-175', 'car-178', 'car-185', 'car-194', 'car-200', 'car-201', 'car-210', 'car-211', 'car-220', 'car-225', 'car-227', 'car-229', 'car-239', 'car-264', 'car-273', 'car-276', 'car-283', 'car-293', 'car-295', 'car-302', 'car-311', 'car-316', 'car-319', 'car-320', 'car-323', 'car-326', 'car-335', 'car-346', 'car-353', 'car-357', 'car-366', 'car-367', 'car-371', 'car-373', 'car-380', 'car-387', 'car-391', 'car-397', 'car-406', 'car-412', 'car-413', 'car-420', 'car-423', 'car-455', 'car-466', 'car-467', 'car-469', 'car-478', 'car-483', 'car-487', 'car-488', 'car-491', 'car-497', 'car-500', 'car-501', 'car-505', 'car-510', 'car-514', 'car-532', 'car-548', 'car-549', 'car-570', 'car-571', 'car-573', 'car-574', 'car-582', 'car-590', 'car-596', 'car004', 'car008', 'car016', 'car037', 'car038', 'car039', 'car040', 'car072', 'car076', 'car077', 'car079', 'car085', 'car108', 'car120', 'car123', 'car129', 'car152', 'car165', 'car168', 'car176', 'car179', 'car186', 'car191', 'car199', 'car237', 'car238', 'car244', 'car249', 'car251', 'car252', 'car254', 'car257', 'car258', 'car260', 'car262', 'car270', 'car272', 'car285', 'car287', 'car292', 'car299', 'car307', 'car312', 'car321', 'car336', 'car338', 'car342', 'car344', 'car352', 'car354', 'car364', 'car372', 'car382', 'car384', 'car386', 'car390', 'car395', 'car401', 'car403', 'car408', 'car409', 'car414', 'car428', 'car431', 'car441', 'car470', 'car474', 'car489', 'car495', 'car516', 'car518', 'car519', 'car526', 'car528', 'car529', 'car542', 'car545', 'car554', 'car562', 'car566', 'car579', 'car587']

Vehicle_ID
 CAR-010     10
 CAR-014      9
 CAR-015      8
 CAR-027     12
 CAR-034      8
             ..
car554       12
car562       13
car566       14
car579       11
car587        9
Name: count, Length: 601, dtype: int64

In [309]:
# Clean Vehicle_ID: trim whitespace, normalize separators, canonical uppercase

# Strip leading/trailing whitespace
df['Vehicle_ID'] = df['Vehicle_ID'].str.strip()

# Normalize separators: double hyphens -> single, underscores -> hyphens
df['Vehicle_ID'] = df['Vehicle_ID'].str.replace('--', '-', regex=False)
df['Vehicle_ID'] = df['Vehicle_ID'].str.replace('_', '-', regex=False)

# Insert hyphen between letters and digits where missing (e.g., CAR08 -> CAR-08)
df['Vehicle_ID'] = df['Vehicle_ID'].str.replace(r'([A-Za-z])\s+(\d)', r'\1-\2', regex=True)
df['Vehicle_ID'] = df['Vehicle_ID'].str.replace(r'([A-Za-z])(\d)', r'\1-\2', regex=True)

# Convert to uppercase canonical form
df['Vehicle_ID'] = df['Vehicle_ID'].str.upper()

# Fix CAR-004 -> CAR-04 to match 2-digit format
df['Vehicle_ID'] = df['Vehicle_ID'].replace('CAR-004', 'CAR-04')

# Convert 'UNKNOWN' to NaN, flag invalid IDs
df['Vehicle_ID_Invalid'] = df['Vehicle_ID'].isna() | (df['Vehicle_ID'] == 'UNKNOWN')
df.loc[df['Vehicle_ID'] == 'UNKNOWN', 'Vehicle_ID'] = pd.NA

print("Cleaned Vehicle_IDs:")
print(sorted(df['Vehicle_ID'].dropna().unique()))
print(f"\n{df['Vehicle_ID'].value_counts().sort_index()}")

Cleaned Vehicle_IDs:
['CAR-001', 'CAR-002', 'CAR-003', 'CAR-005', 'CAR-006', 'CAR-007', 'CAR-008', 'CAR-009', 'CAR-010', 'CAR-011', 'CAR-012', 'CAR-013', 'CAR-014', 'CAR-015', 'CAR-016', 'CAR-017', 'CAR-018', 'CAR-019', 'CAR-020', 'CAR-021', 'CAR-022', 'CAR-023', 'CAR-024', 'CAR-025', 'CAR-026', 'CAR-027', 'CAR-028', 'CAR-029', 'CAR-030', 'CAR-031', 'CAR-032', 'CAR-033', 'CAR-034', 'CAR-035', 'CAR-036', 'CAR-037', 'CAR-038', 'CAR-039', 'CAR-04', 'CAR-040', 'CAR-041', 'CAR-042', 'CAR-043', 'CAR-044', 'CAR-045', 'CAR-046', 'CAR-047', 'CAR-048', 'CAR-049', 'CAR-050', 'CAR-051', 'CAR-052', 'CAR-053', 'CAR-054', 'CAR-055', 'CAR-056', 'CAR-057', 'CAR-058', 'CAR-059', 'CAR-060', 'CAR-061', 'CAR-062', 'CAR-063', 'CAR-064', 'CAR-065', 'CAR-066', 'CAR-067', 'CAR-068', 'CAR-069', 'CAR-070', 'CAR-071', 'CAR-072', 'CAR-073', 'CAR-074', 'CAR-075', 'CAR-076', 'CAR-077', 'CAR-078', 'CAR-079', 'CAR-080', 'CAR-081', 'CAR-082', 'CAR-083', 'CAR-084', 'CAR-085', 'CAR-086', 'CAR-087', 'CAR-088', 'CAR-089', 'CAR-090', 'CAR-091', 'CAR-092', 'CAR-093', 'CAR-094', 'CAR-095', 'CAR-096', 'CAR-097', 'CAR-098', 'CAR-099', 'CAR-100', 'CAR-101', 'CAR-102', 'CAR-103', 'CAR-104', 'CAR-105', 'CAR-106', 'CAR-107', 'CAR-108', 'CAR-109', 'CAR-110', 'CAR-111', 'CAR-112', 'CAR-113', 'CAR-114', 'CAR-115', 'CAR-116', 'CAR-117', 'CAR-118', 'CAR-119', 'CAR-120', 'CAR-121', 'CAR-122', 'CAR-123', 'CAR-124', 'CAR-125', 'CAR-126', 'CAR-127', 'CAR-128', 'CAR-129', 'CAR-130', 'CAR-131', 'CAR-132', 'CAR-133', 'CAR-134', 'CAR-135', 'CAR-136', 'CAR-137', 'CAR-138', 'CAR-139', 'CAR-140', 'CAR-141', 'CAR-142', 'CAR-143', 'CAR-144', 'CAR-145', 'CAR-146', 'CAR-147', 'CAR-148', 'CAR-149', 'CAR-150', 'CAR-151', 'CAR-152', 'CAR-153', 'CAR-154', 'CAR-155', 'CAR-156', 'CAR-157', 'CAR-158', 'CAR-159', 'CAR-160', 'CAR-161', 'CAR-162', 'CAR-163', 'CAR-164', 'CAR-165', 'CAR-166', 'CAR-167', 'CAR-168', 'CAR-169', 'CAR-170', 'CAR-171', 'CAR-172', 'CAR-173', 'CAR-174', 'CAR-175', 'CAR-176', 'CAR-177', 'CAR-178', 'CAR-179', 'CAR-180', 'CAR-181', 'CAR-182', 'CAR-183', 'CAR-184', 'CAR-185', 'CAR-186', 'CAR-187', 'CAR-188', 'CAR-189', 'CAR-190', 'CAR-191', 'CAR-192', 'CAR-193', 'CAR-194', 'CAR-195', 'CAR-196', 'CAR-197', 'CAR-198', 'CAR-199', 'CAR-200', 'CAR-201', 'CAR-202', 'CAR-203', 'CAR-204', 'CAR-205', 'CAR-206', 'CAR-207', 'CAR-208', 'CAR-209', 'CAR-210', 'CAR-211', 'CAR-212', 'CAR-213', 'CAR-214', 'CAR-215', 'CAR-216', 'CAR-217', 'CAR-218', 'CAR-219', 'CAR-220', 'CAR-221', 'CAR-222', 'CAR-223', 'CAR-224', 'CAR-225', 'CAR-226', 'CAR-227', 'CAR-228', 'CAR-229', 'CAR-230', 'CAR-231', 'CAR-232', 'CAR-233', 'CAR-234', 'CAR-235', 'CAR-236', 'CAR-237', 'CAR-238', 'CAR-239', 'CAR-240', 'CAR-241', 'CAR-242', 'CAR-243', 'CAR-244', 'CAR-245', 'CAR-246', 'CAR-247', 'CAR-248', 'CAR-249', 'CAR-250', 'CAR-251', 'CAR-252', 'CAR-253', 'CAR-254', 'CAR-255', 'CAR-256', 'CAR-257', 'CAR-258', 'CAR-259', 'CAR-260', 'CAR-261', 'CAR-262', 'CAR-263', 'CAR-264', 'CAR-265', 'CAR-266', 'CAR-267', 'CAR-268', 'CAR-269', 'CAR-270', 'CAR-271', 'CAR-272', 'CAR-273', 'CAR-274', 'CAR-275', 'CAR-276', 'CAR-277', 'CAR-278', 'CAR-279', 'CAR-280', 'CAR-281', 'CAR-282', 'CAR-283', 'CAR-284', 'CAR-285', 'CAR-286', 'CAR-287', 'CAR-288', 'CAR-289', 'CAR-290', 'CAR-291', 'CAR-292', 'CAR-293', 'CAR-294', 'CAR-295', 'CAR-296', 'CAR-297', 'CAR-298', 'CAR-299', 'CAR-300', 'CAR-301', 'CAR-302', 'CAR-303', 'CAR-304', 'CAR-305', 'CAR-306', 'CAR-307', 'CAR-308', 'CAR-309', 'CAR-310', 'CAR-311', 'CAR-312', 'CAR-313', 'CAR-314', 'CAR-315', 'CAR-316', 'CAR-317', 'CAR-318', 'CAR-319', 'CAR-320', 'CAR-321', 'CAR-322', 'CAR-323', 'CAR-324', 'CAR-325', 'CAR-326', 'CAR-327', 'CAR-328', 'CAR-329', 'CAR-330', 'CAR-331', 'CAR-332', 'CAR-333', 'CAR-334', 'CAR-335', 'CAR-336', 'CAR-337', 'CAR-338', 'CAR-339', 'CAR-340', 'CAR-341', 'CAR-342', 'CAR-343', 'CAR-344', 'CAR-345', 'CAR-346', 'CAR-347', 'CAR-348', 'CAR-349', 'CAR-350', 'CAR-351', 'CAR-352', 'CAR-353', 'CAR-354', 'CAR-355', 'CAR-356', 'CAR-357', 'CAR-358', 'CAR-359', 'CAR-360', 'CAR-361', 'CAR-362', 'CAR-363', 'CAR-364', 'CAR-365', 'CAR-366', 'CAR-367', 'CAR-368', 'CAR-369', 'CAR-370', 'CAR-371', 'CAR-372', 'CAR-373', 'CAR-374', 'CAR-375', 'CAR-376', 'CAR-377', 'CAR-378', 'CAR-379', 'CAR-380', 'CAR-381', 'CAR-382', 'CAR-383', 'CAR-384', 'CAR-385', 'CAR-386', 'CAR-387', 'CAR-388', 'CAR-389', 'CAR-390', 'CAR-391', 'CAR-392', 'CAR-393', 'CAR-394', 'CAR-395', 'CAR-396', 'CAR-397', 'CAR-398', 'CAR-399', 'CAR-400', 'CAR-401', 'CAR-402', 'CAR-403', 'CAR-404', 'CAR-405', 'CAR-406', 'CAR-407', 'CAR-408', 'CAR-409', 'CAR-410', 'CAR-411', 'CAR-412', 'CAR-413', 'CAR-414', 'CAR-415', 'CAR-416', 'CAR-417', 'CAR-418', 'CAR-419', 'CAR-420', 'CAR-421', 'CAR-422', 'CAR-423', 'CAR-424', 'CAR-425', 'CAR-426', 'CAR-427', 'CAR-428', 'CAR-429', 'CAR-430', 'CAR-431', 'CAR-432', 'CAR-433', 'CAR-434', 'CAR-435', 'CAR-436', 'CAR-437', 'CAR-438', 'CAR-439', 'CAR-440', 'CAR-441', 'CAR-442', 'CAR-443', 'CAR-444', 'CAR-445', 'CAR-446', 'CAR-447', 'CAR-448', 'CAR-449', 'CAR-450', 'CAR-451', 'CAR-452', 'CAR-453', 'CAR-454', 'CAR-455', 'CAR-456', 'CAR-457', 'CAR-458', 'CAR-459', 'CAR-460', 'CAR-461', 'CAR-462', 'CAR-463', 'CAR-464', 'CAR-465', 'CAR-466', 'CAR-467', 'CAR-468', 'CAR-469', 'CAR-470', 'CAR-471', 'CAR-472', 'CAR-473', 'CAR-474', 'CAR-475', 'CAR-476', 'CAR-477', 'CAR-478', 'CAR-479', 'CAR-480', 'CAR-481', 'CAR-482', 'CAR-483', 'CAR-484', 'CAR-485', 'CAR-486', 'CAR-487', 'CAR-488', 'CAR-489', 'CAR-490', 'CAR-491', 'CAR-492', 'CAR-493', 'CAR-494', 'CAR-495', 'CAR-496', 'CAR-497', 'CAR-498', 'CAR-499', 'CAR-500', 'CAR-501', 'CAR-502', 'CAR-503', 'CAR-504', 'CAR-505', 'CAR-506', 'CAR-507', 'CAR-508', 'CAR-509', 'CAR-510', 'CAR-511', 'CAR-512', 'CAR-513', 'CAR-514', 'CAR-515', 'CAR-516', 'CAR-517', 'CAR-518', 'CAR-519', 'CAR-520', 'CAR-521', 'CAR-522', 'CAR-523', 'CAR-524', 'CAR-525', 'CAR-526', 'CAR-527', 'CAR-528', 'CAR-529', 'CAR-530', 'CAR-531', 'CAR-532', 'CAR-533', 'CAR-534', 'CAR-535', 'CAR-536', 'CAR-537', 'CAR-538', 'CAR-539', 'CAR-540', 'CAR-541', 'CAR-542', 'CAR-543', 'CAR-544', 'CAR-545', 'CAR-546', 'CAR-547', 'CAR-548', 'CAR-549', 'CAR-550', 'CAR-551', 'CAR-552', 'CAR-553', 'CAR-554', 'CAR-555', 'CAR-556', 'CAR-557', 'CAR-558', 'CAR-559', 'CAR-560', 'CAR-561', 'CAR-562', 'CAR-563', 'CAR-564', 'CAR-565', 'CAR-566', 'CAR-567', 'CAR-568', 'CAR-569', 'CAR-570', 'CAR-571', 'CAR-572', 'CAR-573', 'CAR-574', 'CAR-575', 'CAR-576', 'CAR-577', 'CAR-578', 'CAR-579', 'CAR-580', 'CAR-581', 'CAR-582', 'CAR-583', 'CAR-584', 'CAR-585', 'CAR-586', 'CAR-587', 'CAR-588', 'CAR-589', 'CAR-590', 'CAR-591', 'CAR-592', 'CAR-593', 'CAR-594', 'CAR-595', 'CAR-596', 'CAR-597', 'CAR-598', 'CAR-599', 'CAR-600']

Vehicle_ID
CAR-001     6
CAR-002     8
CAR-003    10
CAR-005    11
CAR-006     8
           ..
CAR-596     8
CAR-597     7
CAR-598     7
CAR-599    12
CAR-600     8
Name: count, Length: 600, dtype: int64

In [310]:
# Validate: all non-null IDs should match CAR-XX or CAR-XXX
valid_ids = df['Vehicle_ID'].dropna()
pattern_match = valid_ids.str.match(r'^CAR-\d{2,3}$')

print(f"Valid IDs: {len(valid_ids)} | Matching pattern: {pattern_match.sum()} | Non-matching: {(~pattern_match).sum()}")
if (~pattern_match).any():
    print(f"Non-matching: {valid_ids[~pattern_match].unique()}")

print(f"\nUnique Vehicle_IDs — Before: {unique_vid}, After: {df['Vehicle_ID'].nunique()}")
print(f"Invalid (NaN) Vehicle_IDs: {df['Vehicle_ID'].isna().sum()}")

Valid IDs: 4986 | Matching pattern: 4986 | Non-matching: 0

Unique Vehicle_IDs — Before: 601, After: 600
Invalid (NaN) Vehicle_IDs: 14

## 2. Timestamp normalization; invalid minutes fix; duration must be positive.

In [311]:
import re
def fix_invalid_minutes(ts):
    if pd.isna(ts):
        return ts  
    match = re.search(r'(\d{1,2}):(\d{2})', str(ts))
    
    if match:
        hour = int(match.group(1))
        minute = int(match.group(2))
        
        if minute > 59:
            hour += minute // 60
            minute = minute % 60
        
        if hour > 23:
            hour = hour % 24
            
        ts = re.sub(r'\d{1,2}:\d{2}', f"{hour}:{minute:02d}", str(ts))
            
    return ts

In [312]:
df["Pickup_TS"] = df["Pickup_TS"].apply(fix_invalid_minutes)
df["Pickup_TS"] = df["Pickup_TS"].str.replace("/", "-", regex=False).str.replace("T", " ", regex=False)
df["Pickup_TS"] = pd.to_datetime(df["Pickup_TS"], format='mixed', dayfirst=True)

df["Return_TS"] = df["Return_TS"].apply(fix_invalid_minutes)
df["Return_TS"] = df["Return_TS"].str.replace("/", "-", regex=False).str.replace("T", " ", regex=False)
df["Return_TS"] = pd.to_datetime(df["Return_TS"], format='mixed', dayfirst=True)

df["Booking_TS"] = df["Booking_TS"].apply(fix_invalid_minutes)
df["Booking_TS"] = df["Booking_TS"].str.replace("/", "-", regex=False).str.replace("T", " ", regex=False)
df["Booking_TS"] = pd.to_datetime(df["Booking_TS"], format='mixed', dayfirst=True)

print(df[['Pickup_TS', 'Return_TS', 'Booking_TS']].head(7).to_string(index=False))

          Pickup_TS           Return_TS          Booking_TS
2025-02-18 07:56:00 2025-02-18 09:56:00 2025-02-13 07:56:00
2025-02-16 20:56:00 2025-02-17 07:56:00 2025-02-08 20:56:00
2025-03-10 00:07:00 2025-03-12 23:07:00 2025-09-03 00:07:00
2025-11-01 02:16:00 2025-01-11 22:16:00 2025-01-04 02:16:00
2025-09-05 04:22:00 2025-10-05 11:22:00 2025-04-05 04:22:00
2025-05-30 08:10:00 2025-05-31 09:10:00 2025-05-27 09:18:00
2025-06-08 14:21:00 2025-09-06 08:02:00 2025-06-05 14:21:00

## 3. Odometer numeric extraction and unit unification (km)

In [313]:
def clean_odometer(value):

    if pd.isna(value):
        return pd.NA

    # convert to string
    value = str(value)

    # remove commas
    value = value.replace(",", "")

    # remove non-numeric characters
    value = re.sub(r'[^0-9.]', '', value)

    if value == "":
        return pd.NA

    return float(value)

# Apply function to both odometer columns
df['Odo_Start'] = df['Odo_Start'].apply(clean_odometer)
df['Odo_End'] = df['Odo_End'].apply(clean_odometer)

print((df[['Odo_Start','Odo_End']].head(7)).to_string(index=False))

 Odo_Start  Odo_End
   57815.0  58065.0
   77762.0  77766.0
   57856.0  58238.0
   59967.0  60239.0
   24261.0  24524.0
   36184.0  36211.0
   41914.0  41881.0

## 4. Fuel level normalization (50%→0.5)

In [314]:
# Remove % symbol
df["Fuel_Level"] = df["Fuel_Level"].astype(str).str.replace("%", "")

# Convert column to numeric
df["Fuel_Level"] = pd.to_numeric(df["Fuel_Level"], errors="coerce")

# Convert percentage values to fraction
df.loc[df["Fuel_Level"] > 1, "Fuel_Level"] = df["Fuel_Level"] / 100

df['Fuel_Level'].unique()

array([0.1 ,  nan, 0.3 , 0.5 , 0.75, 1.  , 0.25])

## 5. Rate parsing to numeric daily rate; currency normalization.

In [315]:
usd_to_inr = 92
eur_to_inr = 106

def clean_rate(val):

    if pd.isna(val):
        return pd.NA

    val = str(val).replace(",", "").strip()

    # USD values
    if "USD" in val or "$" in val:
        num = re.findall(r'\d+', val)
        if num:
            return int(num[0]) * usd_to_inr

    # EURO values
    if "EUR" in val or "€" in val:
        num = re.findall(r'\d+', val)
        if num:
            return int(num[0]) * eur_to_inr

    # INR values
    num = re.findall(r'\d+', val)
    if num:
        return int(num[0])

    return pd.NA


df["Rate"] = df["Rate"].apply(clean_rate)
print((df[['Rate']].head(7)).to_string(index=False))

Rate
1840
2000
2000
1500
2300
2500
2000

## 6. City normalization to canonical names.

In [316]:
# Remove spaces
df["City"] = df["City"].str.strip()

# Convert everything to lowercase
df["City"] = df["City"].str.lower()

# Replace unknown and missing values with NA
df["City"] = df["City"].replace("unknown", pd.NA)

# Map inconsistent names to standard names
city_mapping = {
    "blr": "bengaluru",
    "bangalore": "bengaluru",
    "bengaluru": "bengaluru",

    "mum": "mumbai",
    "bombay": "mumbai",
    "mumbai": "mumbai",

    "del": "delhi",
    "delhi": "delhi",
    "new delhi": "delhi",

    "chn": "chennai",
    "chennai": "chennai",

}

df["City"] = df["City"].replace(city_mapping)

# Convert to title case
df["City"] = df["City"].str.title()

df["City"].value_counts()

# Check unique city values after cleaning
print(df["City"].unique())

<StringArray>
['Delhi', 'Mumbai', 'Bengaluru', 'Chennai', nan]
Length: 5, dtype: str

## 7. Duplicate reservation dedup (same ID).

In [317]:
print(f"Duplicate Reservation_IDs: {df['Reservation_ID'].duplicated().sum()}")
df = df.drop_duplicates(subset='Reservation_ID', keep='first')
print(f"Shape after dedup: {df.shape}")

Duplicate Reservation_IDs: 473
Shape after dedup: (4527, 22)

## 8. Return before pickup rule validation.

In [318]:
swap_mask = df["Return_TS"] < df["Pickup_TS"]

df.loc[swap_mask, ["Pickup_TS","Return_TS"]] = \
df.loc[swap_mask, ["Return_TS","Pickup_TS"]].values

df["Duration_Hours"] = (df["Return_TS"] - df["Pickup_TS"]).dt.total_seconds() / 3600
invalid_duration = df[df["Duration_Hours"] < 0]
equal_mask = df["Return_TS"] == df["Pickup_TS"]
df.loc[equal_mask, ["Pickup_TS", "Return_TS"]] = pd.NaT

print(df[['Pickup_TS', 'Return_TS', 'Duration_Hours']].head(7).to_string(index=False))

          Pickup_TS           Return_TS  Duration_Hours
2025-02-18 07:56:00 2025-02-18 09:56:00        2.000000
2025-02-16 20:56:00 2025-02-17 07:56:00       11.000000
2025-03-10 00:07:00 2025-03-12 23:07:00       71.000000
2025-01-11 22:16:00 2025-11-01 02:16:00     7036.000000
2025-09-05 04:22:00 2025-10-05 11:22:00      727.000000
2025-05-30 08:10:00 2025-05-31 09:10:00       25.000000
2025-06-08 14:21:00 2025-09-06 08:02:00     2153.683333

## 9. Payment method standardization (UPI/CARD/CASH/WALLET).

In [319]:
df["Payment"] = df["Payment"].astype(str).str.lower().str.strip()

payment_dict = {
    "upi": "UPI",
    
    "credit card": "CARD",
    "debit card": "CARD",
    "card": "CARD",
    "netbanking": "CARD",
    
    "cash": "CASH",
    
    "wallet": "WALLET",
    
    "-": pd.NA,
    "nan": pd.NA
}

df["Payment"] = df["Payment"].replace(payment_dict)
print(df["Payment"].unique())

<StringArray>
['CASH', 'UPI', nan, 'CARD', 'WALLET']
Length: 5, dtype: str

## 10. Mileage sanity check (End ≥ Start)

In [320]:
mileage_check = df[['Reservation_ID','Odo_Start','Odo_End']].copy()

# Swap Odo_Start and Odo_End where End < Start (likely data entry error)
odo_swap_mask = df['Odo_End'] < df['Odo_Start']
df.loc[odo_swap_mask, ['Odo_Start', 'Odo_End']] = df.loc[odo_swap_mask, ['Odo_End', 'Odo_Start']].values

# Verify no invalid mileages remain
mileage_check = df[['Reservation_ID','Odo_Start','Odo_End']].copy()
mileage_check['Mileage_Valid'] = mileage_check['Odo_End'] >= mileage_check['Odo_Start']
print(f"Invalid mileages remaining: {(~mileage_check['Mileage_Valid']).sum()}")
print(mileage_check.head(7).to_string(index=False))

Invalid mileages remaining: 0
Reservation_ID  Odo_Start  Odo_End  Mileage_Valid
     RES-00001    57815.0  58065.0           True
     RES-00002    77762.0  77766.0           True
     RES-00003    57856.0  58238.0           True
     RES-00004    59967.0  60239.0           True
     RES-00005    24261.0  24524.0           True
     RES-00006    36184.0  36211.0           True
     RES-00007    41881.0  41914.0           True

## 11. Refueling event detection vs fuel change and distance.

In [321]:
# Normalize Fuel_Level (re-normalize in case of any remaining % values)
df["Fuel_Level"] = df["Fuel_Level"].astype(str).str.replace("%", "", regex=False)
df["Fuel_Level"] = pd.to_numeric(df["Fuel_Level"], errors="coerce")

# Convert percentage values to fraction
df.loc[df["Fuel_Level"] > 1, "Fuel_Level"] = df["Fuel_Level"] / 100

# Prepare validity mask and distance driven directly on main dataframe
valid_odo_mask = df["Odo_End"] >= df["Odo_Start"]
df["Distance_Driven"] = pd.NA
df.loc[valid_odo_mask, "Distance_Driven"] = (
    df.loc[valid_odo_mask, "Odo_End"] - df.loc[valid_odo_mask, "Odo_Start"]
)

# Detect refuel events directly on main dataframe
sorted_idx = df.sort_values(["Vehicle_ID", "Odo_Start"]).index
fuel_diff = df.loc[sorted_idx].groupby("Vehicle_ID")["Fuel_Level"].diff()
refuel_flag = (fuel_diff > 0).map({True: "Refueled", False: "No Refuel"})

df["Refuel_Event"] = pd.NA
df.loc[refuel_flag.index, "Refuel_Event"] = refuel_flag
df.loc[~valid_odo_mask, "Refuel_Event"] = pd.NA

print((df[['Refuel_Event']].head(7)).to_string(index=False))

Refuel_Event
   No Refuel
   No Refuel
    Refueled
   No Refuel
   No Refuel
   No Refuel
   No Refuel

## 12. Vehicle availability overlap checks.

In [322]:
df = df.sort_values(['Vehicle_ID','Pickup_TS'])

df['Prev_Return'] = df.groupby('Vehicle_ID')['Return_TS'].shift(1)
df['Overlap_Flag'] = df['Pickup_TS'] < df['Prev_Return']
df['Overlap_Flag'].value_counts()

Overlap_Flag
False    3235
True     1292
Name: count, dtype: int64

## 13. Damage / Incident Log Linkage to Reservation

In [323]:
#inspect
df[['Reservation_ID','Vehicle_ID','Customer_ID','Damage_Flag','Notes']].head()

#Extract rows where damage was reported
damage_logs = df[
    df['Damage_Flag'].notna() &
    (df['Damage_Flag'] != 'None')
]

#Create a separate incident log dataset
incident_log = damage_logs[['Reservation_ID','Vehicle_ID','Customer_ID','Damage_Flag','Notes']].copy()

#Check for records where damage is flagged but notes are missing
missing_notes = incident_log[incident_log['Notes'].isna()|(incident_log['Notes'].str.strip() == "")]

print("Damage incidents missing description:", len(missing_notes))

#Detect possible damage mentioned in notes but flag is 'None'
possible_damage = df[
    (df['Damage_Flag'] == 'None') &
    (df['Notes'].str.contains('damage|scratch|dent|crack', case=False, na=False))
]

print("Possible misclassified incidents:", len(possible_damage))

#Display the final incident log dataset
incident_log.head(15)
df['Notes'].unique()

Damage incidents missing description: 500
Possible misclassified incidents: 0

<StringArray>
['Customer reported minor scratch on door',
          'Car returned in good condition',
               'Low fuel warning observed',
         'Tyre pressure alert during trip',
             'AC performance slightly low',
                                       nan,
    'Vehicle returned late due to traffic',
         'Customer requested early pickup',
              'Interior cleaning required',
  'Navigation system malfunction reported',
            'Customer satisfied with ride']
Length: 11, dtype: str

## 14. Driver license masking and validation (if present).

In [324]:
#validation
def validate_license(x):
    if pd.isna(x):
        return None
    
    x = str(x)
    
    if re.match(r"DL-\d{10}$", x):
        return x
    else:
        return None

df["Driver_License"] = df["Driver_License"].apply(validate_license)

#masking
def mask_license(x):
    if pd.isna(x):
        return None
    
    return x[:7] + "XXXXXX"

df["Driver_License"] = df["Driver_License"].apply(mask_license)


# Valid masked DLs
valid_dl = df[df["Driver_License"].notna()][["Driver_License"]].head(5)

print("Valid Masked DLs:")
print(valid_dl.to_string(index=False))

# Null / invalid DLs
null_dl = df[df["Driver_License"].isna()][["Driver_License"]].head(5)

print("\nNull / Invalid DLs:")
print(null_dl.to_string(index=False))

Valid Masked DLs:
Driver_License
 DL-9542XXXXXX
 DL-9194XXXXXX
 DL-8187XXXXXX
 DL-3438XXXXXX
 DL-3438XXXXXX

Null / Invalid DLs:
Empty DataFrame
Columns: [Driver_License]
Index: []

## 15. Promo/coupon code validation & expiry checks.

In [325]:
# convert pickup timestamp
df["Pickup_TS"] = pd.to_datetime(df["Pickup_TS"], errors="coerce")

# promo expiry dictionary
promo_expiry = {
    "NEW10": "2026-03-31",
    "DISC20": "2026-02-28",
    "SAVE50": "2026-06-30",
    "WELCOME5": "2026-01-31"
}

# convert expiry values to datetime
promo_expiry = {k: pd.to_datetime(v) for k, v in promo_expiry.items()}

# map expiry date to dataset
df["Promo_Expiry"] = df["Promo_Code"].map(promo_expiry)
df["Promo_Status"] = "Valid"

# invalid promo codes
df.loc[df["Promo_Code"].notna() & df["Promo_Expiry"].isna(), "Promo_Status"] = "Invalid_Code"

# expired promo codes
df.loc[(df["Promo_Expiry"].notna()) & (df["Pickup_TS"] > df["Promo_Expiry"]), "Promo_Status"] = "Expired"

print((df[['Promo_Code','Promo_Expiry','Promo_Status']].head(7)).to_string(index=False))

Promo_Code Promo_Expiry Promo_Status
    DISC20   2026-02-28        Valid
  WELCOME5   2026-01-31        Valid
    DISC20   2026-02-28        Valid
     NEW10   2026-03-31        Valid
    DISC20   2026-02-28        Valid
    DISC20   2026-02-28        Valid
       NaN          NaT        Valid

## 16. Telematics GPS join and jitter smoothing.

In [326]:
# check duplicates
df[['GPS_Lat', 'GPS_Lon']].duplicated().sum()

# convert to numeric and handle missing values
df['GPS_Lat'] = pd.to_numeric(
    df['GPS_Lat'].astype(str).str.strip().str.replace(r"^'+|'+$", "", regex=True),
    errors='coerce'
 )
df['GPS_Lon'] = pd.to_numeric(
    df['GPS_Lon'].astype(str).str.strip().str.replace(r"^'+|'+$", "", regex=True),
    errors='coerce'
 )
df['GPS_Lat'] = df['GPS_Lat'].interpolate()
df['GPS_Lon'] = df['GPS_Lon'].interpolate()

# smooth jitter and round to 4 decimals
df['GPS_Lat'] = df['GPS_Lat'].rolling(window=3, min_periods=1).mean().round(4)
df['GPS_Lon'] = df['GPS_Lon'].rolling(window=3, min_periods=1).mean().round(4)

print(df[['GPS_Lat', 'GPS_Lon']].dtypes)
print((df[['GPS_Lat','GPS_Lon']].head(7)).to_string(index=False))

GPS_Lat    float64
GPS_Lon    float64
dtype: object
 GPS_Lat  GPS_Lon
 12.9141  77.6273
 12.9001  77.5888
 12.8954  77.5817
 12.8989  77.5811
 12.9032  77.6057
 12.9240  77.6290
 12.9208  77.6246

## 17. Speeding/harsh events normalization from telematics.

In [327]:
df["Speed"] = df["Speed"].astype(str)

# Remove Units (kmh and km/h)
df["Speed"] = df["Speed"].str.replace("km/h","", regex=False)
df["Speed"] = df["Speed"].str.replace("kmh","", regex=False)

# Convert "fast" to Numeric Speed. Since "fast" means driving faster than normal, we convert it to 90 km/h.
df["Speed"] = df["Speed"].replace("fast", 90)
df["Speed"] = pd.to_numeric(df["Speed"], errors="coerce")

# Create Driver Behavior Classification
def classify_speed(speed):
    if pd.isna(speed):
        return "Unknown"
    elif speed <= 80:
        return "Normal Driving"
    elif speed <= 100:
        return "Fast Driving"
    else:
        return "Speeding"

df["Driver_Behavior"] = df["Speed"].apply(classify_speed)

print(df[["Speed","Driver_Behavior"]].head(7).to_string(index=False))

 Speed Driver_Behavior
 128.0        Speeding
  49.0  Normal Driving
  84.0    Fast Driving
  76.0  Normal Driving
   NaN         Unknown
  90.0    Fast Driving
  28.0  Normal Driving

## 18. PII redaction in notes and feedback.

In [328]:
df['Notes'] = df['Notes'].str.replace(r'\b\d{10}\b', '[REDACTED]', regex=True)
df['Notes'] = df['Notes'].str.replace(r'\S+@\S+', '[REDACTED]', regex=True)
df['Notes'] = df['Notes'].str.replace(r'\b[A-Z0-9]{8,}\b', '[REDACTED]', regex=True)

print(df[['Notes']].head(7).to_string(index=False))

                                  Notes
Customer reported minor scratch on door
         Car returned in good condition
         Car returned in good condition
              Low fuel warning observed
        Tyre pressure alert during trip
            AC performance slightly low
            AC performance slightly low

## 19. Rate plan mapping to master tariffs.

In [329]:
df['Rate'] = df['Rate'].astype(str)
df['Rate'] = df['Rate'].str.replace('[^0-9.]', '', regex=True)
df['Rate'] = pd.to_numeric(df['Rate'], errors='coerce')

print((df[['Rate']].head(7)).to_string(index=False))

  Rate
2000.0
2300.0
1840.0
2000.0
1500.0
2300.0
   NaN

## 20. Tax/GST computation validation.

In [331]:
# Tax/GST computation validation.

df["Rate"] = pd.to_numeric(df["Rate"], errors="coerce")
df["Total_Amount"] = (df["Rate"] * 1.18).round(2)

print((df[['Total_Amount']].head(7)).to_string(index=False))

 Total_Amount
       2360.0
       2714.0
       2171.2
       2360.0
       1770.0
       2714.0
          NaN

Additional Cleaning

In [332]:
df['Vehicle_ID'].unique()

df["Pickup_TS"] = pd.to_datetime(df["Pickup_TS"])
df["Return_TS"] = pd.to_datetime(df["Return_TS"])

df["Pickup_TS"] = df["Pickup_TS"].fillna(df["Pickup_TS"].mean())
df["Return_TS"] = df["Return_TS"].fillna(df["Return_TS"].mean())
df["Pickup_TS"] = df["Pickup_TS"].fillna(df["Pickup_TS"].mean())
df["Return_TS"] = df["Return_TS"].fillna(df["Return_TS"].mean())

df["Fuel_Level"] = df["Fuel_Level"].fillna(df["Fuel_Level"].mean())
df["Rate"] = df["Rate"].fillna(df["Rate"].mean())


df["Promo_Code"] = df["Promo_Code"].fillna(df["Promo_Code"].mode()[0])
df["City"] = df["City"].fillna(df["City"].mode()[0])


df["Speed"] = df["Speed"].fillna(df["Speed"].median())
df["Payment"] = df["Payment"].fillna(df["Payment"].mode()[0])

df["Damage_Flag"] = df["Damage_Flag"].fillna("None")

df["Notes"] = df["Notes"].fillna("No Notes")

df["Duration_Hours"] = df["Duration_Hours"].round(2)

In [ ]:
df["Booking_TS"] = pd.to_datetime(df["Booking_TS"])
df["Pickup_TS"] = pd.to_datetime(df["Pickup_TS"])

df.loc[df["Booking_TS"] > df["Pickup_TS"], "Booking_TS"] = df["Pickup_TS"] - pd.Timedelta(days=1)
print(df.head(7).to_string(index=False))

Reservation_ID Customer_ID Vehicle_ID Vehicle_Class Booking_Status          Booking_TS           Pickup_TS           Return_TS  Odo_Start  Odo_End  Fuel_Level        Rate Promo_Code    City  GPS_Lat  GPS_Lon  Speed Payment Driver_License Damage_Flag                                   Notes  Vehicle_ID_Invalid  Duration_Hours Distance_Driven Refuel_Event         Prev_Return  Overlap_Flag Promo_Expiry Promo_Status Driver_Behavior  Total_Amount
     RES-00003   CUST-1181    CAR-001        Suzuki      Completed 2025-03-09 00:07:00 2025-03-10 00:07:00 2025-03-12 23:07:00    57856.0  58238.0        0.30 2000.000000     DISC20   Delhi  12.9141  77.6273  128.0     UPI  DL-9542XXXXXX       Minor Customer reported minor scratch on door               False            71.0           382.0     Refueled                 NaT         False   2026-02-28        Valid        Speeding        2360.0
     RES-03655   CUST-0243    CAR-001        Suzuki      Completed 2025-04-12 06:48:00 2025-04-13 06:48:00 2025-04-14 10:48:00    79962.0  80173.0        0.30 2300.000000   WELCOME5  Mumbai  12.9001  77.5888   49.0  WALLET  DL-9194XXXXXX       Major          Car returned in good condition               False            28.0           211.0    No Refuel 2025-03-12 23:07:00         False   2026-01-31        Valid  Normal Driving        2714.0
     RES-01774   CUST-1755    CAR-001        Suzuki      Cancelled 2025-04-13 00:12:00 2025-04-15 00:12:00 2025-04-15 03:12:00    57390.0  57599.0        0.10 1840.000000     DISC20  Mumbai  12.8954  77.5817   84.0    CARD  DL-8187XXXXXX       Minor          Car returned in good condition               False             3.0           209.0    No Refuel 2025-04-14 10:48:00         False   2026-02-28        Valid    Fast Driving        2171.2
     RES-03809   CUST-0799    CAR-001        Suzuki      Cancelled 2025-06-05 00:50:00 2025-06-14 00:50:00 2025-06-15 14:50:00    37275.0  37463.0        0.50 2000.000000      NEW10 Chennai  12.8989  77.5811   76.0    CARD  DL-3438XXXXXX       Minor               Low fuel warning observed               False            38.0           188.0    No Refuel 2025-04-15 03:12:00         False   2026-03-31        Valid  Normal Driving        2360.0
     RES-01293   CUST-0799    CAR-001        Suzuki      Cancelled 2025-05-01 21:46:00 2025-09-01 21:46:00 2025-12-01 00:46:00    70972.0  70992.0        0.75 1500.000000     DISC20  Mumbai  12.9032  77.6057   90.0    CARD  DL-3438XXXXXX       Minor         Tyre pressure alert during trip               False          2163.0            20.0     Refueled 2025-06-15 14:50:00         False   2026-02-28        Valid         Unknown        1770.0
     RES-02593   CUST-1437    CAR-001        Suzuki      Completed 2025-07-06 20:51:00 2025-09-06 20:51:00 2025-10-06 07:51:00    60442.0  60884.0        0.30 2300.000000     DISC20   Delhi  12.9240  77.6290   90.0    CARD  DL-9254XXXXXX        None             AC performance slightly low               False           707.0           442.0    No Refuel 2025-12-01 00:46:00          True   2026-02-28        Valid    Fast Driving        2714.0
     RES-01461   CUST-0555    CAR-002        Toyota      Completed 2024-12-23 20:04:00 2025-01-01 20:04:00 2025-01-02 20:04:00    39548.0  39636.0        0.10 1835.274591      NEW10   Delhi  12.9208  77.6246   28.0     UPI  DL-8144XXXXXX       Minor             AC performance slightly low               False            24.0            88.0    No Refuel                 NaT         False          NaT        Valid  Normal Driving           NaN

In [ ]:
df.loc[df["Booking_Status"] == "Cancelled", "Odo_End"] = df["Odo_Start"]
df.loc[df["Booking_Status"] == "Cancelled", "Total_Amount"] = 0

df["Total_Amount"] = df["Total_Amount"].fillna(df["Total_Amount"].mean())

In [ ]:
df["Fuel_Level"] = df["Fuel_Level"].round(2)
df["Rate"] = df["Rate"].round(2)
df["Total_Amount"] = df["Total_Amount"].round(2)

In [ ]:
df["Distance_Driven"] = df["Odo_End"] - df["Odo_Start"]
df["Vehicle_ID"] = df["Vehicle_ID"].fillna("CAR-600")
df.loc[df["Promo_Expiry"].isnull(), "Promo_Status"] = "Invalid"

In [ ]:
import numpy as np
from geopy.geocoders import Nominatim
import time

# Initialize geocoder
geolocator = Nominatim(user_agent="city_lat_long_generator")

# Get unique cities
cities = df["City"].dropna().unique()
city_coords = {}

# Get base coordinates for each city
for city in cities:
    try:
        location = geolocator.geocode(city)
        if location:
            city_coords[city] = (location.latitude, location.longitude)
        else:
            city_coords[city] = (np.nan, np.nan)
        time.sleep(1)
    except:
        city_coords[city] = (np.nan, np.nan)

# Function to generate random nearby coordinates
def generate_random_coords(city):
    lat, lon = city_coords.get(city, (np.nan, np.nan))

    if pd.isna(lat) or pd.isna(lon):
        return pd.Series([np.nan, np.nan])

    lat_random = lat + np.random.uniform(-0.02, 0.02)
    lon_random = lon + np.random.uniform(-0.02, 0.02)

    # round to 4 decimal places
    lat_random = round(lat_random, 4)
    lon_random = round(lon_random, 4)

    return pd.Series([lat_random, lon_random])

# Apply to dataframe
df[["GPS_Lat", "GPS_Lon"]] = df["City"].apply(generate_random_coords)

In [ ]:
# Created expected_hours for overstay simulation.
# 10% rows get +4 to +9 hours over Duration_Hours, remaining rows keep Duration_Hours.
import numpy as np

df["expected_hours"] = pd.to_numeric(df["Duration_Hours"], errors="coerce")
valid_mask = df["expected_hours"].notna()
eligible_idx = df.index[valid_mask]

n_boost = int(len(eligible_idx) * 0.10)
if n_boost > 0:
    boost_idx = df.loc[eligible_idx].sample(n=n_boost, random_state=42).index
    rng = np.random.default_rng(42)
    bump = np.random.default_rng(42).uniform(4, 9, size=n_boost)
    df.loc[boost_idx, "expected_hours"] = df.loc[boost_idx, "expected_hours"].to_numpy() + bump

print(f"expected_hours created for {len(eligible_idx):,} eligible rows")
print(f"Rows bumped by +4..+9 hours: {n_boost:,}")
print(df[["Duration_Hours", "expected_hours"]].head(7))

expected_hours created for 4,527 eligible rows
Rows bumped by +4..+9 hours: 452
      Duration_Hours  expected_hours
2               71.0            71.0
3654            28.0            28.0
1773             3.0             3.0
3808            38.0            38.0
1292          2163.0          2163.0
2592           707.0           707.0
1460            24.0            24.0

In [ ]:
# Save cleaned dataset to CSV
df.to_csv("../Datasets/car_rental_cleaned_dataset.csv", index=False)
print("Cleaned dataset saved to 'car_rental_cleaned_dataset.csv'")
print(f"Final dataset shape: {df.shape}")
print(f"Columns: {df.columns.tolist()}")

Cleaned dataset saved to 'car_rental_cleaned_dataset.csv'
Final dataset shape: (4527, 32)
Columns: ['Reservation_ID', 'Customer_ID', 'Vehicle_ID', 'Vehicle_Class', 'Booking_Status', 'Booking_TS', 'Pickup_TS', 'Return_TS', 'Odo_Start', 'Odo_End', 'Fuel_Level', 'Rate', 'Promo_Code', 'City', 'GPS_Lat', 'GPS_Lon', 'Speed', 'Payment', 'Driver_License', 'Damage_Flag', 'Notes', 'Vehicle_ID_Invalid', 'Duration_Hours', 'Distance_Driven', 'Refuel_Event', 'Prev_Return', 'Overlap_Flag', 'Promo_Expiry', 'Promo_Status', 'Driver_Behavior', 'Total_Amount', 'expected_hours']